your-chart:
  enabled: true
  replicaCount: 2

  image:
    repository: httpd
    tag: "2.4"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: app2.local
        paths:
          - path: /
            pathType: Prefix

  config:
    LOG_LEVEL: info
    FEATURE_FLAG: "false"

  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70

  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    httpGet:
      path: /
      port: http

  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    httpGet:
      path: /
      port: http

  startup:
    initialDelaySeconds: 3
    periodSeconds: 10
    httpGet:
      path: /
      port: http
